### ISSUE TITLE
Arrow keys are not working properly

### ISSUE THREAD

**Issue by anoop-gupt** [PublicisSapient/accessible-ecommerce-demo#237]
Arrow key interaction is not working smoothly it is scrolling the page while user is on Dropdown Navigation.

**Comment by alisonrae** [comment]
It is not a typical paradigm to need to use arrows to navigate on a flyout menu on a webpage. That is more of a software paradigm. It's not how things need to work on the web. Using the tab key works just fine, and most users will try that on the web. On the web, we want to let people use their down arrow to scroll down the page. Let me know if you have documentation indicating otherwise and I will look it over. Check out the "Use parent as toggle" menu shown here on the w3 site: https://www.w3.org/WAI/tutorials/menus/flyout/

**Comment by anoop-gupt** [comment]
Thanks for the clarification and yes 'Tabs' are the primary medium for traversing. 
I was talking about interaction distraction while using arrow keys.
Just check this example 
https://www.w3.org/WAI/tutorials/menus/application-menus-code/
Here page is not scrolling while using arrow keys for a flyout. However, the demo is awesome and helpful in many ways.
Appreciate.

**Comment by alisonrae** [comment]
Hi Anoop, yes, the example you provide is called “application menu” because it applies to software applications, to my understanding. If you try using an application like Word, that’s how it works with the keyboard. The flyout menu example is meant to apply to flyout menus on the web. The down arrow is supposed to scroll the page in a web browser. It is expected behaviour. Please let me know if you’ve read otherwise, I’d love to learn more if I’m mistaken on this point. Thanks for using the demo and taking the time to comment!
